export const StaticData = {
Meta_title:"Matalan stores in the UK | Matalan",
Meta_description:"Find your local Matalan store with our store locator. See opening times, directions and information for our stores across the UK.",
locator_breadcrumb:"Store Locator",
FindLocationtext:"Find your nearest Matalan store",
Usemylocation:"Use my current location",
UsemylocationDesktop:"Use my location",
Search:"Search",
Brandname:"Matalan",
miles:"miles",
tempClosed:"Temporarily Closed",
StoreDetailbtn:"STORE DETAILS",
Storehighlight:"Store Highlights",
Days:"Days",
Hours:"Hours",
Minutes:"Minutes",
Seconds:"Seconds",
getDirection:"Get directions",
AllStores:"Matalan Stores in",
NearStoretext:"Nearby stores",
FAQheading:"How can we help ?",
AllLocationtext:"View All Location",
PaySecure:"Pay securely with",
PagenotFound:"Oops!",
cantfind_page:"We're really sorry, we can't find the page you're looking for",
Youcouldtry:"You could try",
Previuspage:"Going back to the previous page",
homePage:"Going back to the homepage",
StoreFinder:"Store Finder",
FAQs:"FAQs",
DownloadApp:"Download Our App",
cookie:"our use of cookies",
CookiebuttonText:"Got IT",
Closed:"Closed",
DayofWeek:"Day of the Week",
Reopenmessage:"Message - The store is temporarily closed. It will reopen at",
Address:"Address",
Telephone:"Telephone",
Holdiay:"See holiday hours*",
Holdiay_popup:"See holiday hours",

}